project:
  title: "TEC-IN2039 Data Visualization"
  type: website
  output-dir: docs
editor: visual

website:
  title: "IN2039 Data Visualization"
  page-navigation: true
  sidebar:
    contents:
      - href: TEC-IN2039-Website.qmd
        text: Home

author: 
  - name: Alan R. Vázquez
    affiliations:
      - name: Departamento de Ingeniería Industrial
        
format:
  html:
    toc: true
    shift-heading-level-by: 1

  revealjs:
    output-ext: "slides.html"
    chalkboard: true
    multiplex: true
    footer: "Tecnológico de Monterrey"
    logo: IN2039_logo.png
    css: style.css
    slide-number: True
revealjs-plugins:
  - pointer 

